// Real Foodborne Outbreak Data Integration for OutbreakWatch
// This replaces the sample data with live data from foodborne_outbreaks.json

class RealFoodborneMonitor {
    constructor() {
        this.outbreaks = [];
        this.lastUpdated = null;
        this.updateInterval = 6 * 60 * 60 * 1000; // 6 hours in milliseconds
    }

    async loadRealFoodborneData() {
        try {
            console.log('Loading real foodborne outbreak data...');
            
            // Fetch the real data generated by the scraper
            const response = await fetch('./foodborne_outbreaks.json?t=' + new Date().getTime());
            
            if (response.ok) {
                const data = await response.json();
                this.outbreaks = data.outbreaks || [];
                this.lastUpdated = data.last_updated;
                
                console.log(`Loaded ${this.outbreaks.length} real foodborne outbreaks`);
                console.log(`Data last updated: ${this.lastUpdated}`);
                
                return true;
            } else {
                console.log('Real foodborne data not available, using fallback');
                this.loadFallbackData();
                return false;
            }
        } catch (error) {
            console.error('Error loading real foodborne data:', error);
            this.loadFallbackData();
            return false;
        }
    }

    loadFallbackData() {
        // Fallback to sample data if real data unavailable
        this.outbreaks = [
            {
                pathogen: "Salmonella Typhimurium",
                product: "Chocolate Products",
                countries: ["Multiple European Countries"],
                regions: ["Europe"],
                cases: null,
                source_organization: "ECDC",
                severity_level: "Medium",
                status: "Under Investigation",
                last_updated: new Date().toISOString()
            }
        ];
        console.log('Using fallback foodborne outbreak data');
    }

    updateFoodborneStatus() {
        const banner = document.getElementById('foodborneAlertBanner');
        const count = document.getElementById('foodborneAlertCount');
        const summary = document.getElementById('foodborneAlertSummary');
        
        if (this.outbreaks.length > 0) {
            banner.classList.add('active');
            count.textContent = `${this.outbreaks.length} outbreak${this.outbreaks.length === 1 ? '' : 's'}`;
            
            // Create summary based on severity
            const highSeverity = this.outbreaks.filter(o => o.severity_level === 'High').length;
            const globalOutbreaks = this.outbreaks.filter(o => o.countries.length > 1).length;
            
            if (highSeverity > 0) {
                summary.textContent = `${this.outbreaks.length} active outbreaks detected globally (${highSeverity} high severity)`;
            } else if (globalOutbreaks > 0) {
                summary.textContent = `${this.outbreaks.length} active outbreaks detected globally (${globalOutbreaks} multi-country)`;
            } else {
                summary.textContent = `${this.outbreaks.length} active foodborne outbreaks detected globally`;
            }
        } else {
            banner.classList.remove('active');
        }
    }

    showFoodborneDetails() {
        if (this.outbreaks.length === 0) {
            alert('No active foodborne outbreaks currently detected.\n\nData sources: WHO, ECDC, Health Canada, CDC\nLast checked: ' + new Date().toLocaleString());
            return;
        }

        let alertText = "Active Global Foodborne Outbreak Alerts:\n\n";
        
        // Sort by severity (High > Medium > Low)
        const sortedOutbreaks = this.outbreaks.sort((a, b) => {
            const severityOrder = { 'High': 0, 'Medium': 1, 'Low': 2 };
            return severityOrder[a.severity_level] - severityOrder[b.severity_level];
        });

        sortedOutbreaks.forEach((outbreak, index) => {
            const severityIcon = outbreak.severity_level === 'High' ? '🔴' : 
                                outbreak.severity_level === 'Medium' ? '🟡' : '🟢';
            
            alertText += `${index + 1}. ${severityIcon} ${outbreak.pathogen} in ${outbreak.product}\n`;
            alertText += `   Countries: ${outbreak.countries.slice(0, 3).join(", ")}${outbreak.countries.length > 3 ? '...' : ''}\n`;
            
            if (outbreak.cases) {
                alertText += `   Cases: ${outbreak.cases}`;
            } else {
                alertText += `   Cases: Under investigation`;
            }
            
            if (outbreak.deaths) alertText += `, Deaths: ${outbreak.deaths}`;
            if (outbreak.hospitalizations) alertText += `, Hospitalizations: ${outbreak.hospitalizations}`;
            
            alertText += `\n   Source: ${outbreak.source_organization}`;
            alertText += `\n   Status: ${outbreak.status}`;
            alertText += `\n   Severity: ${outbreak.severity_level}\n\n`;
        });
        
        alertText += `Data Sources: WHO Disease Outbreak News, ECDC, Health Canada, CDC\n`;
        alertText += `Global Foodborne Surveillance Network\n`;
        
        if (this.lastUpdated) {
            const updateTime = new Date(this.lastUpdated).toLocaleString();
            alertText += `Last Updated: ${updateTime}`;
        } else {
            alertText += `Last Updated: ${new Date().toLocaleString()}`;
        }
        
        alert(alertText);
    }

    getHighPriorityOutbreaks() {
        return this.outbreaks.filter(outbreak => 
            outbreak.severity_level === 'High' || 
            outbreak.countries.length > 3 ||
            (outbreak.cases && outbreak.cases > 50)
        );
    }

    getRecentOutbreaks(days = 7) {
        const cutoffDate = new Date();
        cutoffDate.setDate(cutoffDate.getDate() - days);
        
        return this.outbreaks.filter(outbreak => {
            const outbreakDate = new Date(outbreak.date_reported || outbreak.last_updated);
            return outbreakDate >= cutoffDate;
        });
    }

    generateSummaryStats() {
        if (this.outbreaks.length === 0) return null;

        const stats = {
            total: this.outbreaks.length,
            high_severity: this.outbreaks.filter(o => o.severity_level === 'High').length,
            multi_country: this.outbreaks.filter(o => o.countries.length > 1).length,
            top_pathogens: this.getTopPathogens(),
            top_regions: this.getTopRegions(),
            last_updated: this.lastUpdated
        };

        return stats;
    }

    getTopPathogens() {
        const pathogenCounts = {};
        this.outbreaks.forEach(outbreak => {
            pathogenCounts[outbreak.pathogen] = (pathogenCounts[outbreak.pathogen] || 0) + 1;
        });
        
        return Object.entries(pathogenCounts)
            .sort(([,a], [,b]) => b - a)
            .slice(0, 3)
            .map(([pathogen, count]) => ({ pathogen, count }));
    }

    getTopRegions() {
        const regionCounts = {};
        this.outbreaks.forEach(outbreak => {
            outbreak.regions.forEach(region => {
                regionCounts[region] = (regionCounts[region] || 0) + 1;
            });
        });
        
        return Object.entries(regionCounts)
            .sort(([,a], [,b]) => b - a)
            .slice(0, 3)
            .map(([region, count]) => ({ region, count }));
    }

    async autoRefresh() {
        await this.loadRealFoodborneData();
        this.updateFoodborneStatus();
        
        // Schedule next refresh
        setTimeout(() => this.autoRefresh(), this.updateInterval);
    }
}

// Global instance
const realFoodborneMonitor = new RealFoodborneMonitor();

// Replace the old foodborne functions
function showFoodborneDetails() {
    realFoodborneMonitor.showFoodborneDetails();
}

function updateFoodborneStatus() {
    realFoodborneMonitor.updateFoodborneStatus();
}

// Enhanced initialization
document.addEventListener('DOMContentLoaded', async function() {
    // Load real foodborne data
    await realFoodborneMonitor.loadRealFoodborneData();
    realFoodborneMonitor.updateFoodborneStatus();
    
    // Start auto-refresh cycle
    realFoodborneMonitor.autoRefresh();
    
    // Log summary stats
    const stats = realFoodborneMonitor.generateSummaryStats();
    if (stats) {
        console.log('Foodborne Outbreak Statistics:');
        console.log(`- Total outbreaks: ${stats.total}`);
        console.log(`- High severity: ${stats.high_severity}`);
        console.log(`- Multi-country: ${stats.multi_country}`);
        console.log(`- Top pathogens: ${stats.top_pathogens.map(p => p.pathogen).join(', ')}`);
    }
});
